# Generated by Django 6.0.5 on 2026-06-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendency',
            name='field_id',
        ),
        migrations.AddField(
            model_name='tendency',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.educationbranch', verbose_name='کد رشته'),
        ),
    ]
