"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@&xyh7myeli%ssasho6pw*^0q419ruwtv$@@6#9i5vdf3ke4b2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'docs'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.api.authentication.AuthSessionTokenAuthentication',
        'core.api.authentication.AuthSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'core.api.permissions.IsAuthenticatedAccount',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.api.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# DRF Spectacular Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'آموزشیار — Amoozeshyar API',
    'DESCRIPTION': (
        'REST API کامل برای سامانه آموزشیار شامل ۴۱ انتیتی، احراز هویت، '
        'و APIهای ترکیبی صفحات. مستندات تعاملی از طریق Swagger و ReDoc در دسترس است.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]',
    'TAGS': [
        {'name': 'Health', 'description': 'بررسی سلامت و در دسترس بودن سرویس API'},
        {'name': 'Authentication', 'description': 'ورود، خروج، پروفایل کاربر و بازیابی رمز عبور'},
        {'name': 'Auth Entities', 'description': 'مدیریت نقش‌ها، حساب‌ها، نشست‌ها و تخصیص نقش (فقط مدیر)'},
        {'name': 'Lookup', 'description': 'داده‌های مرجع: مقادیر ثابت، دانشکده، گرایش، نیمسال'},
        {'name': 'Person & Contact', 'description': 'اشخاص و اطلاعات تماس: تلفن، ایمیل، مهارت، آدرس'},
        {'name': 'Profiles', 'description': 'پروفایل اساتید، دانشجویان، کارمندان و علایق پژوهشی'},
        {'name': 'Academic', 'description': 'دروس، کلاس‌ها، امتحانات، نمرات، کارنامه، حضور و غیاب'},
        {'name': 'Finance & Requests', 'description': 'پرداخت‌ها، وام، بورسیه، خوابگاه و درخواست‌های دانشجویی'},
        {'name': 'Library & Misc', 'description': 'کتابخانه، کارآموزی، رویدادها، اطلاعیه‌ها و برنامه‌های آموزشی'},
        {'name': 'Composite Pages', 'description': 'APIهای ترکیبی — یک درخواست برای هر صفحه فرانت‌اند'},
    ],
    'EXTENSIONS_ROOT': {
        'x-tagGroups': [
            {'name': 'عمومی', 'tags': ['Health']},
            {'name': 'احراز هویت', 'tags': ['Authentication', 'Auth Entities']},
            {'name': 'داده‌های پایه', 'tags': ['Lookup', 'Person & Contact', 'Profiles']},
            {'name': 'آموزشی و مالی', 'tags': ['Academic', 'Finance & Requests']},
            {'name': 'سایر', 'tags': ['Library & Misc', 'Composite Pages']},
        ],
    },
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'TokenAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'هدر Authorization با فرمت: Token <session_key>',
            },
            'SessionAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'نشست Django — پس از login با کوکی sessionid نیز قابل استفاده است.',
            },
        },
    },
    'SECURITY': [{'TokenAuth': []}, {'SessionAuth': []}],
    'ENUM_NAME_OVERRIDES': {
        'ApprovalWorkflowStatusEnum': [
            ('pending', 'در انتظار'),
            ('approved', 'تایید شده'),
            ('rejected', 'رد شده'),
        ],
    },
}
